services:
  - type: web
    name: spearo-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_ISSUER_BASE_URL
        sync: false 